# This is a basic workflow to help you get started with Actions

name: Create Issue Branch

# Controls when the workflow will run
on:
  issues: 
    types: [ assigned ]
  pull_request:
    types: [ closed ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: GoDeokHwan/create-issue-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo Branch Name
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
